# Generated by Django 5.0.3 on 2024-05-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_alter_quote_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='session_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
